### ISSUE TITLE
kfp 2.3.0 upgrade `persistenceagent` rock

### ISSUE THREAD

**Issue by misohu** [canonical/pipelines-rocks#137]
### Context

Upgrade the the rock for 2.3.0 kfp

Related to https://github.com/canonical/kfp-operators/issues/581

### What needs to get done

Upgrade the rock

### Definition of Done

1. Rock is upgraded for kfp 2.3.0
2. Rock is on Dockerhub

**Comment by DnPlas** [comment]
No updates were made to the [Dockerfile for tag 2.3.0](https://github.com/kubeflow/pipelines/blob/2.3.0/backend/Dockerfile.persistenceagent), so I'll just bump the source tag and the rock version. Nothing else to do.
