### ISSUE TITLE
Workflows are needed for this repository 

### ISSUE THREAD

**Issue by i-chvets** [canonical/pipelines-rocks#37]
# Description

Main issue: https://github.com/canonical/bundle-kubeflow/issues/692

Workflows are needed for this repository:
- on pull request execute ROCKs sanity tests (a.k.a. smoke tests), peform CVE scans
- on merge publish ROCK

Without integration tests in ROCK repository how do we ensure ROCK is acceptable to be used in charm? Do we publish ROCK regardless as long as it passed sanity tests?

**Comment by orfeas-k** [comment]
This was fixed by #58. Regarding tests, we have https://github.com/canonical/pipelines-rocks/issues/59 in order to add sanity tests.
