### ISSUE TITLE
bump rocks to kfp v2.0.5 in `main`

### ISSUE THREAD

**Issue by ca-scribner** [canonical/pipelines-rocks#69]
### Context

[Charmed Kubeflow 1.8.1](https://github.com/kubeflow/manifests/releases/tag/v1.8.1) bumped kfp to 2.0.5 to implement [this fix](https://github.com/kubeflow/pipelines/pull/10269).  We need to incorporate this update in `main`

### What needs to get done

1. bump all images to 2.0.5

### Definition of Done

.

**Comment by orfeas-k** [comment]
This task has been completed. Regarding `frontend` ROCK, we have issue #80 and it will be tackled as part of it.
